# To run all pre-commit checks, use:
#
#     pre-commit run -a
#
# To install pre-commit hooks that run every time you commit:
#
#     pre-commit install
#

ci:
  autoupdate_commit_msg: "⬆️🪝 update pre-commit hooks"
  autofix_commit_msg: "🎨 pre-commit fixes"
  skip: [mypy]

repos:
  # Standard hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.5.0"
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  # Handling unwanted unicode characters
  - repo: https://github.com/sirosen/texthooks
    rev: "0.6.2"
    hooks:
      - id: fix-ligatures
      - id: fix-smartquotes

  # Check for common mistakes
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal

  # Clean jupyter notebooks
  - repo: https://github.com/srstevenson/nb-clean
    rev: "3.1.0"
    hooks:
      - id: nb-clean
  # Check for spelling
  - repo: https://github.com/codespell-project/codespell
    rev: "v2.2.6"
    hooks:
      - id: codespell
        args: ["-L", "wille,linz,fro"]
        exclude: "mqt/benchviewer/templates/legal.html"

  # Format configuration files with prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.3"
    hooks:
      - id: prettier
        types_or: [yaml, markdown, html, css, javascript, json]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.4
    hooks:
      - id: ruff
        args: ["--fix", "--show-fixes"]
        types_or: [python, pyi, jupyter]
      - id: ruff-format
        types_or: [python, pyi, jupyter]

  # Also run Black on examples in the documentation
  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.16.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==23.*]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
      - id: mypy
        files: ^(src|tests)
        args: []
        additional_dependencies:
          - importlib_resources
          - qubovert
          - pytest==7.4.0
          - types-setuptools
          - setuptools<=65.6.3
          - sympy==1.12
          - numpy==1.23.5
          - dwave-samplers
          - dwave.system
          - docplex==2.25.236
          - qiskit==0.45.3
          - qiskit_optimization==0.4.0
          - qiskit-algorithms==0.2.1
          - qiskit_ibm_runtime==0.14.0
          - matplotlib
          - pandas
          - PyPortfolioOpt
          - scikit-learn

  # Catch common capitalization mistakes
  - repo: local
    hooks:
      - id: disallow-caps
        name: Disallow improper capitalization
        language: pygrep
        entry: PyBind|Numpy|Cmake|CCache|Github|PyTest|Mqt|Tum
        exclude: (.joblib|.pre-commit-config.yaml)

  # Check best practices for scientific Python code
  - repo: https://github.com/scientific-python/cookie
    rev: 2024.04.23
    hooks:
      - id: sp-repo-review
        additional_dependencies: ["repo-review[cli]"]
